// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:demixr_app/models/unmixed_song.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UnmixedSongAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(UnmixedSongAdapter());
  }
}
